### ISSUE TITLE
Strange RAKF violation adding member to SYS2.CMDPROC

### ISSUE THREAD

**Issue by larry770** [mvslovers/tk4rob#1]
TSU    2  RAKF0005 INVALID ATTEMPT TO ACCESS RESOURCE                 
 TSU    2  RAKF000A  HERC01  ,HERC01  ,DATASET ,SYS2.CMDPROC

**Comment by mgrossmann** [comment]
Hi @larry770,

Rob has replaced the SYS2 datasets with SYS3 equivalents.
THis is the reason, why he has protected the SYS2 ones.

Best, Mike

**Comment by robprins** [comment]
Don't write in the SYS2 datasets. They belong to the original TK4- update 08 of Jürgen Winkelmann.
Feel free to use the PUBxxx volumes. The next time you need only the updates. 
I will not touch the PUBxxx volumes. 
Please add the member into SYS3.CMDPROC

Cheers.
Rob

**Comment by larry770** [comment]
This makes sense.
Thanks for this awesome body of work
